routes/web.php
<?php

use Spatie\Sitemap\SitemapGenerator;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::group(['prefix' => 'api'], function () {
    Route::get('/', 'WebsiteController@indexApi')->name('api.index');
    Route::get('category/{category}', 'CategoryController@showApi')->name('api.category.show');
//    Route::get('postcard/{postcard}/category/{category?}', 'PostcardController@showCategoryApi')->name('api.postcard.show');
//    Route::get('feasts', 'CategoryController@feastsApi')->name('api.feasts.list');
    Route::get('kalendar-prazdnikov', 'CategoryController@feastsApi')->name('api.feasts.list');
    Route::get('kalendar-prazdnikov/{month}', 'CategoryController@feastApi')->name('api.feasts.show');
    Route::get('catalog', 'CategoryController@catalogApi')->name('api.catalog.list');
    Route::get('info/{name}', 'WebsiteController@infoApi')->name('api.info.page');
    Route::group([ 'middleware' => ['isCategory'] ], function() {
        Route::get('{category}/{postcardOrCategory?}/{postcard?}', 'CategoryController@showApi')->name('api.category.show');
    });
});

Route::get('sitemap/generate', 'WebsiteController@generateSitemap')->name('sitemap.generate');

Route::group(['middleware' => ['auth', 'isModer'], 'prefix' => 'admin', 'as' => 'admin.'], function () {
    Route::get('/', 'Admin\AdminController@index')->name('index');
    Route::resource('categories', 'Admin\CategoryController');
    Route::resource('category-backgrounds', 'Admin\CategoryBackgroundController');
    Route::resource('category-backgrounds-categories', 'Admin\CategoryBackgroundCategoryController');
    Route::resource('postcards', 'Admin\PostcardController');
    Route::resource('feasts', 'Admin\FeastController');
    Route::group(['prefix' => 'parser', 'as' => 'parser.'], function () {
        Route::get('/', 'Admin\ParserController@index')->name('index');
        Route::get('/make', 'Admin\ParserController@make')->name('make');
        Route::get('/categories', 'Admin\ParserController@categories')->name('categories');
        Route::get('/create-postcard', 'Admin\ParserController@createPostcard')->name('createPostcard');
        Route::get('/delete-postcard', 'Admin\ParserController@deletePostcard')->name('deletePostcard');
    });
    Route::group(['middleware' => ['auth', 'isAdmin']], function () {
        Route::resource('users', 'Admin\UserController');
        Route::resource('info-pages', 'Admin\InfoPageController');
    });
});

Auth::routes();

Route::get('/', 'WebsiteController@index')->name('index');
Route::get('kalendar-prazdnikov', 'CategoryController@feasts')->name('feasts.list');
Route::get('kalendar-prazdnikov/{month}', 'CategoryController@feast')->name('feasts.show');
Route::get('catalog', 'CategoryController@catalog')->name('catalog.list');
Route::get('info/{name}', 'WebsiteController@info')->name('info.page');
Route::group([ 'middleware' => ['isCategory'] ], function() {
    Route::get('{category}/{postcardOrCategory?}/{postcard?}', 'CategoryController@show')->name('category.show');
});

resources/views/admin/index.blade.php
@extends('admin.layouts.app')

@section('content')

@endsection

resources/views/admin/parser.blade.php
@extends('admin.layouts.app')

@section('content')
    <div id="vue">
        @verbatim
            <div class="form-group">
                <label for="exampleInputEmail1">Адрес сайта:</label>
                <input type="text" class="form-control" id="exampleInputEmail1" placeholder="https://website.com"
                       v-model:value="url" :disabled="states.loading">
                <button @click.prevent="getWebsiteData()" type="button" class="btn btn-primary mb-2 mt-2"
                        :disabled="states.loading">Начать парсинг
                </button>
            </div>
            <div class="form-group">
                <label>Категории для добавления:</label>
                <select class="form-control multi-categories" multiple="multiple"
                        id="u_categories" style="display: none">
                    @endverbatim
                    @foreach($categories as $c)
                        <option value="{{ $c->id }}">{{ $c->name }}<-{{ $c->parent->name ?? 'Праздники' }}</option>
                    @endforeach
                    @verbatim
                </select>
            </div>
            <table class="table" v-if="page != null">
                <thead>
                <tr>
                    <th scope="col">#</th>
                    <th scope="col">Название</th>
                    <th scope="col">Действие</th>
                </tr>
                </thead>
                <tbody>
                <tr v-for="(r, i) in page">
                    <td>
                        <img :src="r.src" :alt="r.alt" style="max-width: 200px;max-height: 200px">
                    </td>
                    <td>
                        <input type="text" class="form-control" v-model="r.alt">
                        <input type="text" class="form-control" v-model="r.src">
                    </td>
                    <td>
                        <button v-if="r.id == -1" class="btn btn-primary" @click="createPostcard(r, i)">Сохранить</button>
                        <button v-if="r.id != -1" class="btn btn-danger" @click="deletePostcard(r, i)">Удалить</button>
                    </td>
                </tr>
                </tbody>
            </table>
        @endverbatim
    </div>
@endsection

@push('scripts')
    <script src="https://cdn.jsdelivr.net/npm/vue/dist/vue.js"></script>
    <script src="https://unpkg.com/axios/dist/axios.min.js"></script>
    <script>
        var app = new Vue({
            el: '#vue',
            data: function () {
                return {
                    url: 'https://otkritkiok.ru/pojelanie/936939075258?utm=category2',
                    page: null,
                    selectedCategories: [],
                    states: {
                        loading: false,
                    },
                    categories: [],
                }
            },
            methods: {
                getCategories: function () {
                    var that = this;
                    that.states.loading = true;
                    axios({
                        method: 'get',
                        url: '{{ route('admin.parser.categories') }}'
                    })
                        .then(function (response) {
                            that.categories = response.data;
                            $(".multi-categories").dashboardCodeBsMultiSelect();
                        })
                        .catch(function (error) {
                            alert(error);
                        })
                        .finally(function () {
                            that.states.loading = false;
                        })
                },
                getWebsiteData: function () {
                    var that = this;
                    that.states.loading = true;
                    axios({
                        method: 'get',
                        url: '{{ route('admin.parser.make') }}',
                        params: {
                            website_url: that.url,
                        }
                    })
                        .then(function (response) {
                            that.page = response.data;
                        })
                        .catch(function (error) {
                            alert(error);
                        })
                        .finally(function () {
                            that.states.loading = false;
                        })
                },
                createPostcard: function (elem, i) {
                    var that = this;
                    var categroies = $('#u_categories').val();
                    axios({
                        method: 'get',
                        url: '{{ route('admin.parser.createPostcard') }}',
                        params: {
                            name: elem.alt,
                            path: elem.src,
                            categories: categroies,
                        }
                    })
                        .then(function (response) {
                            that.page[i].id = response.data.id;
                        })
                        .catch(function (error) {
                            alert(error);
                        })
                        .finally(function () {
                            that.states.loading = false;
                        })
                },
                deletePostcard: function (elem, i) {
                    var that = this;
                    var categroies = $('#u_categories').val();
                    axios({
                        method: 'get',
                        url: '{{ route('admin.parser.deletePostcard') }}',
                        params: {
                            postcard_id: elem.id,
                        }
                    })
                        .then(function (response) {
                            that.page[i].id = -1;
                        })
                        .catch(function (error) {
                            alert(error);
                        })
                        .finally(function () {
                            that.states.loading = false;
                        })
                }
            },
            mounted: function () {
                this.getCategories();
            }
        });
    </script>
@endpush