routes/web.php
<?php

use Spatie\Sitemap\SitemapGenerator;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::group(['prefix' => 'api'], function () {
    Route::get('/', 'WebsiteController@indexApi')->name('api.index');
    Route::get('category/{category}', 'CategoryController@showApi')->name('api.category.show');
//    Route::get('postcard/{postcard}/category/{category?}', 'PostcardController@showCategoryApi')->name('api.postcard.show');
//    Route::get('feasts', 'CategoryController@feastsApi')->name('api.feasts.list');
    Route::get('kalendar-prazdnikov', 'CategoryController@feastsApi')->name('api.feasts.list');
    Route::get('kalendar-prazdnikov/{month}', 'CategoryController@feastApi')->name('api.feasts.show');
    Route::get('catalog', 'CategoryController@catalogApi')->name('api.catalog.list');
    Route::get('info/{name}', 'WebsiteController@infoApi')->name('api.info.page');
    Route::group([ 'middleware' => ['isCategory'] ], function() {
        Route::get('{category}/{postcardOrCategory?}/{postcard?}', 'CategoryController@showApi')->name('api.category.show');
    });
});

Route::get('sitemap/generate', 'WebsiteController@generateSitemap')->name('sitemap.generate');

Route::group(['middleware' => ['auth', 'isModer'], 'prefix' => 'admin', 'as' => 'admin.'], function () {
    Route::get('/', 'Admin\AdminController@index')->name('index');
    Route::resource('categories', 'Admin\CategoryController');
    Route::resource('category-backgrounds', 'Admin\CategoryBackgroundController');
    Route::resource('category-backgrounds-categories', 'Admin\CategoryBackgroundCategoryController');
    Route::resource('postcards', 'Admin\PostcardController');
    Route::resource('feasts', 'Admin\FeastController');
    Route::group(['prefix' => 'parser', 'as' => 'parser.'], function () {
        Route::get('/', 'Admin\ParserController@index')->name('index');
        Route::get('/make', 'Admin\ParserController@make')->name('make');
        Route::get('/categories', 'Admin\ParserController@categories')->name('categories');
        Route::get('/create-postcard', 'Admin\ParserController@createPostcard')->name('createPostcard');
        Route::get('/delete-postcard', 'Admin\ParserController@deletePostcard')->name('deletePostcard');
    });
    Route::group(['middleware' => ['auth', 'isAdmin']], function () {
        Route::resource('users', 'Admin\UserController');
        Route::resource('info-pages', 'Admin\InfoPageController');
    });
});

Auth::routes();

Route::get('/', 'WebsiteController@index')->name('index');
Route::get('kalendar-prazdnikov', 'CategoryController@feasts')->name('feasts.list');
Route::get('kalendar-prazdnikov/{month}', 'CategoryController@feast')->name('feasts.show');
Route::get('catalog', 'CategoryController@catalog')->name('catalog.list');
Route::get('info/{name}', 'WebsiteController@info')->name('info.page');
Route::group([ 'middleware' => ['isCategory'] ], function() {
    Route::get('{category}/{postcardOrCategory?}/{postcard?}', 'CategoryController@show')->name('category.show');
});

app/User.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password', 'role_id'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    public function getIsSuperAttribute() {
        if($this->role_id == 1)
            return true;
        else
            return false;
    }

    public function getIsModerAttribute() {
        if($this->role_id == 1 || $this->role_id == 2)
            return true;
        else
            return false;
    }

    public function getRoleNameAttribute() {
        if($this->attributes['role_id'] == 1)
            return 'Администратор';
        else if($this->attributes['role_id'] == 2)
            return 'Модератор';
        return 'Не установлена';
    }
}

class UserRole extends Model {

}

resources/views/admin/layouts/app.blade.php
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Scripts -->
    <script src="{{ mix('/js/app.js') }}" defer></script>

<!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
{{--    <link href="https://fonts.googleapis.com/css?family=Open+Sans" rel="stylesheet">--}}

<!-- Styles -->
    <!-- include summernote css/js -->
    <link href="{{ mix('/css/app.css') }}" rel="stylesheet">
    @stack('styles')
</head>
<body>
<div id="app">
    <nav class="container navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="{{ route('admin.index') }}">Администратор</a>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <!-- Right Side Of Navbar -->
            <ul class="navbar-nav ml-auto">
                <!-- Authentication Links -->
                @guest
                    <li class="nav-item">
                        <a class="nav-link" href="{{ route('login') }}">Вход</a>
                    </li>
                    @if (Route::has('register'))
                        <li class="nav-item">
                            <a class="nav-link" href="{{ route('register') }}">Регистрация</a>
                        </li>
                    @endif
                @else
                    <li class="nav-item dropdown">
                        <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button"
                           data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                            {{ Auth::user()->name }} <span class="caret"></span>
                        </a>

                        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                            <a href="{{ route('index') }}" class="dropdown-item">На сайт</a>
                            <a class="dropdown-item" href="{{ route('logout') }}"
                               onclick="event.preventDefault();
                                                             document.getElementById('logout-form').submit();">
                                Выход
                            </a>

                            <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                @csrf
                            </form>
                        </div>
                    </li>
                @endguest
            </ul>
        </div>
    </nav>
</div>
{{--        <nav class="navbar navbar-expand-md navbar-light bg-white shadow-sm">--}}
{{--            <div class="container">--}}
{{--                <a class="navbar-brand" href="{{ url('/') }}">--}}
{{--                    {{ config('app.name', 'Laravel') }}--}}
{{--                </a>--}}
{{--                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">--}}
{{--                    <span class="navbar-toggler-icon"></span>--}}
{{--                </button>--}}

{{--                <div class="collapse navbar-collapse" id="navbarSupportedContent">--}}
{{--                    <!-- Left Side Of Navbar -->--}}
{{--                    <ul class="navbar-nav mr-auto">--}}

{{--                    </ul>--}}

{{--                    <!-- Right Side Of Navbar -->--}}
{{--                    <ul class="navbar-nav ml-auto">--}}
{{--                        <!-- Authentication Links -->--}}
{{--                        @guest--}}
{{--                            <li class="nav-item">--}}
{{--                                <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>--}}
{{--                            </li>--}}
{{--                            @if (Route::has('register'))--}}
{{--                                <li class="nav-item">--}}
{{--                                    <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>--}}
{{--                                </li>--}}
{{--                            @endif--}}
{{--                        @else--}}
{{--                            <li class="nav-item dropdown">--}}
{{--                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>--}}
{{--                                    {{ Auth::user()->name }} <span class="caret"></span>--}}
{{--                                </a>--}}

{{--                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">--}}
{{--                                    <a class="dropdown-item" href="{{ route('logout') }}"--}}
{{--                                       onclick="event.preventDefault();--}}
{{--                                                     document.getElementById('logout-form').submit();">--}}
{{--                                        {{ __('Logout') }}--}}
{{--                                    </a>--}}

{{--                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">--}}
{{--                                        @csrf--}}
{{--                                    </form>--}}
{{--                                </div>--}}
{{--                            </li>--}}
{{--                        @endguest--}}
{{--                    </ul>--}}
{{--                </div>--}}
{{--            </div>--}}
{{--        </nav>--}}

<main class="py-4">
    <div class="container">
        <div class="row">
            <div id="jquery-accordion-menu" class="jquery-accordion-menu col-md-3">
                <div class="jquery-accordion-menu-header">{{ Auth::user()->role_name }}</div>
                <ul>
                    @foreach(\App\Http\Controllers\Admin\AdminController::getMenu() as $menu)
                        @isset($menu['sub'])
                            <li><a href="#">{{ $menu['name'] }} </a>
                                <ul class="submenu">
                                    @foreach($menu['sub'] as $sub)
                                        <li><a href="{{ $sub['url'] }}">{{ $sub['name'] }} </a></li>
                                    @endforeach
                                </ul>
                            </li>
                        @else
                            <li><a href="{{ $menu['url'] }}">{{ $menu['name'] }} </a></li>
                        @endisset
                    @endforeach
                </ul>
            </div>
            <div class="col-md-9">
                @yield('content')
            </div>
        </div>
    </div>
</main>
</div>
@stack('scripts')
</body>
</html>

resources/views/admin/layouts/edit_form.blade.php
@extends('admin.layouts.app')

@section('content')
    <h3 class="mb-3">
        Редактирование {{ $title ?? '' }}
        <div class="float-right">
            @isset($delete)
                <form action="{{ $delete }}" method="POST">
                    @csrf
                    {{ method_field('delete') }}
                    <button type="submit" class="btn btn-danger">
                        <i class="fa fa-trash"></i>
                    </button>
                </form>
            @endisset
        </div>
    </h3>
    <form action="{{ $form_route }}" enctype="multipart/form-data" method="POST" class="pb-5">
        @csrf
        {{ method_field($method) }}
        @foreach($form as $i => $element)
            <div class="form-group">
                <label
                    for="{{ $element['name'].'_'.$i }}">{{ $element['text'] }}{{ isset($element['required']) && $element['required'] ? '*' : '' }}
                    :</label>
                @if($element['type'] == 'text')
                    <input type="text" class="form-control" id="{{ $element['name'].'_'.$i }}"
                           name="{{ $element['name'] }}"
                           value="{{ $element['value'] ?? '' }}" {{ isset($element['required']) && $element['required'] ? 'required' : '' }}>
                @elseif($element['type'] == 'select')
                    <select class="custom-select" id="{{ $element['name'].'_'.$i }}"
                            name="{{ $element['name'] }}"
                            value="{{ $element['value'] ?? '' }}" {{ isset($element['required']) && $element['required'] ? 'required' : '' }}>
                        <option value>-- Выбрать --</option>
                        @foreach($element['items'] as $k => $val)
                            <option value="{{ $k }}" {{ $val->id == $element['value'] ? 'selected' : '' }}>{{ $val->name
                                ?? '' }}
                            </option>
                        @endforeach
                    </select>
                @elseif($element['type'] == 'image')
                    @isset($element['value'])
                        <div>
                            <img src="{{ $element['value'] }}" alt="..." class="img-thumbnail">
                        </div>
                        <div>
                            <input type="file" id="{{ $element['name'].'_'.$i }}"
                                   accept="image/jpeg,image/png,image/gif"
                                   name="{{ $element['name'] }}"
                                   value="{{ $element['value'] ?? '' }}">
                        </div>
                    @else
                        <div>
                            <input type="file" id="{{ $element['name'].'_'.$i }}"
                                   accept="image/jpeg,image/png,image/gif"
                                   name="{{ $element['name'] }}"
                                   value="{{ $element['value'] ?? '' }}"
                                {{ isset($element['required']) && $element['required'] ? 'required' : '' }}>
                        </div>
                    @endisset
                @elseif($element['type'] == 'textarea')
                    <textarea class="form-control" name="{{ $element['name'] }}"
                              {{ isset($element['required']) && $element['required'] ? 'required' : '' }} rows="3">{{ $element['value'] ?? '' }}</textarea>
                @elseif($element['type'] == 'text-editable')
                    <textarea class="summernote" name="{{ $element['name'] }}"
                              {{ isset($element['required']) && $element['required'] ? 'required' : '' }} rows="3">{{ $element['value'] ?? '' }}</textarea>
                @elseif($element['type'] == 'color')
                    <input type="color" id="{{ $element['name'].'_'.$i }}"
                           accept="image/jpeg,image/png,image/gif"
                           name="{{ $element['name'] }}"
                           value="{{ $element['value'] ?? '' }}"
                        {{ isset($element['required']) && $element['required'] ? 'required' : '' }}>
                @elseif($element['type'] == 'select')
                    <select class="form-control"
                            id="{{ $element['name'].'_'.$i }}"
                            name="{{ $element['name'] }}"
                        {{ isset($element['required']) && $element['required'] ? 'required' : '' }}>
                        @foreach($element['items'] as $k => $val)
                            <option value="{{ $k }}" {{ isset($element['value'][$val->id]) ? 'selected' : '' }}>
                                @isset($element['name_key'])
                                    {{ $val->{$element['name_key']} ?? '' }}
                                @else
                                    {{ $val->name ?? '' }}
                                @endisset
                            </option>
                        @endforeach
                    </select>
                @elseif($element['type'] == 'select-multiple')
                    <select class="form-control multi-select" multiple="multiple" style="display: none;"
                            id="{{ $element['name'].'_'.$i }}"
                            name="{{ $element['name'] }}"
                        {{ isset($element['required']) && $element['required'] ? 'required' : '' }}>
                        @foreach($element['items'] as $k => $val)
                            <option value="{{ $k }}" {{ isset($element['value'][$val->id]) ? 'selected' : '' }}>
                                @isset($element['name_key'])
                                    {{ $val->{$element['name_key']} ?? '' }}
                                @else
                                    {{ $val->name ?? '' }}
                                @endisset
                            </option>
                        @endforeach
                    </select>
                @elseif($element['type'] == 'date')
                    <input type="date" class="form-control" id="{{ $element['name'].'_'.$i }}"
                           name="{{ $element['name'] }}"
                           value="{{ $element['value'] ?? '' }}"
                        {{ isset($element['required']) && $element['required'] ? 'required' : '' }}>
                @endif
            </div>
        @endforeach
        <button class="btn btn-success"><i class="fa fa-save"></i> Сохранить</button>
    </form>
@endsection

@push('styles')
    <style>
        .img-thumbnail {
            max-width: 300px;
        }
    </style>
@endpush
@push('scripts')
    <script>
    </script>
@endpush

resources/views/admin/layouts/table_image_page.blade.php
@extends('admin.layouts.app')

@section('content')
    @include('admin.partials.table_image', ['table' => $table])
@endsection

@push('styles')
    <style>
        th:last-child,
        td:last-child {
            text-align: right;
        }
    </style>
@endpush

resources/views/admin/layouts/table_page.blade.php
@extends('admin.layouts.app')

@section('content')
    @include('admin.partials.table', ['table' => $table])
@endsection

@push('styles')
    <style>
        th:last-child,
        td:last-child {
            text-align: right;
        }
    </style>
@endpush